### ISSUE TITLE
Output error code 1 when downloading packages

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-sdk#12]
# Expected behaviour

Error code 0 when running ```./cooker -d ar71xx/generic```

# Actual behaviour

Error code 1.
Output here: https://travis-ci.org/libremesh/lime-packages/builds/253444589#L623

**Comment by p4u** [comment]
Not sure why cooker returns 1 but on the output there is not any error.

**Comment by nicopace** [comment]
I'd it returns 0 it will comply wirh Unix standards... It's a feature... I can do it in the CI... Or a patch :)
Will try a patch later 

El 18 de julio de 2017 8:03:23 PM GMT+02:00, Pau <notifications@github.com> escribió:
>Not sure why cooker returns 1 but on the output there is not any error.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libremesh/lime-sdk/issues/12#issuecomment-316146805

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by ilario** [comment]
The exit code is forced to zero unless when cooking, so for downloads is also forced to zero. I would call this solved and move discussion on #16.
