### ISSUE TITLE
How do you update the Communities network profiles?

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-sdk#17]
Let's say someone else is mantaining my profle.
Is there any way I can call to update the community profiles from github?
like doing the 'git pull'

**Comment by p4u** [comment]
Yes, git pull is fine. But an automatic procedure should be good to have as an option for the cooker.

**Comment by aparcar** [comment]
isn't `--update-communities` already doing the trick?

**Comment by ilario** [comment]
Yep, I tested and @p4u already fixed this in 14a3d17, closing.
