### ISSUE TITLE
consolidation of package

### ISSUE THREAD

**Issue by dangowrt** [libremesh/lime-sdk#19]
Currently packages are passed to the ImageBuilder by simply appending the string coming from flavours.conf with the PKG environment variable. This is insufficient in case of the user wanting to install a package via PKG variable which is masked by a `-` character in front of the package. In such a case (such as `firewall`) the package cannot be installed via the PKG variable at all.

**Comment by p4u** [comment]
Is this not working for you?

`./cooker -c ar71xx/generic --profile=tl-wdr4300-v1 --extra-pkg="-firewall luci-app-3g"`

**Comment by p4u** [comment]
Ah, ok! You mean that packages which are market with minus on the flavor cannot be installed by the user.

So we need to implement a funcion on cooker to join the package lists and add preference to the user choice.

**Comment by dangowrt** [comment]
Precisely. You got it.

**Comment by p4u** [comment]
implemented on commit https://github.com/libremesh/lime-sdk/commit/75ce2b3b099da646d2dbf1705769fb94a59c2131

So by order of preference:

 1. User defined packages on --extra-pkg
 2. Packages on global PKG var
 3. Community profile packages
 4. Flavor packages
