### ISSUE TITLE
Remove break after option --update-feeds

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-sdk#27]
Currently cooker does not evaluate any option after "--update-feeds" because of break [here](https://github.com/libremesh/lime-sdk/blob/master/cooker#L483).

```
case $1 in
[...]
    --update-feeds)
        update_feeds
        break
```

This can be fixed replacing it with shift. Is this correct @p4u?

**Comment by p4u** [comment]
Yes you'r right, break might be removed.

**Comment by svalo** [comment]
I'd like to take care of this, on which branch should I work?

**Comment by ilario** [comment]
Let's go for master, develop is place for building trunk (and is broken, see #35)
