### ISSUE TITLE
--update-feeds by default?

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-sdk#31]
In my opinion cooker should update the feeds (`--update-feeds`) by default, and having a `--no-update-feeds` required for avoiding this.
This would limit situations where users compile broken formware like [here](https://lists.libremesh.org/pipermail/lime-users/2017-October/000911.html).

**Comment by aparcar** [comment]
Sound good.

**Comment by p4u** [comment]
Agree

**Comment by nicopace** [comment]
I would say it would be relevant to tell the user that there are updates that can be done, but not enforce by default to update.
It is an undesired sideeffect if you want to have reproducible builds, as each time you run build you may get different packages without the parameters changing in your commandline.
I would propose for the system to do a non-destructive action of checking if there were changes that could be applied by fetching but not merging the remote changes.
It is as easy as doing fetch on each git repo, and showing how many commits are from the previous to the current situation.

**Comment by G10h4ck** [comment]
The reproducibility of the builds is guaranted for releases anyway because of tags used for repository feeds, but having to specify manually to update the feeds is quite antipattern in almost any case, so I would merge the related pullrequest

**Comment by nicopace** [comment]
Like the approach... will review the code now.

**Comment by nicopace** [comment]
jej, thought it was a PR... like the approach proposed by @G10h4ck

**Comment by ilario** [comment]
Fixed by #70
