### ISSUE TITLE
promote https://chef.libremesh.org/

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-sdk#32]
The service slowly becomes more stable so some people might like to use the online editor instead of setting up their own builder

* https://imagebuilder.libremesh.org/
* https://ib.libremesh.org/

**Comment by FreifunkUFO** [comment]
would ne nice, to finish some things first. the name is discussed at lime-dev malingliste atm. some parameters are changing atm and some final tests have to be done before giviing it more people for usage.

**Comment by ilario** [comment]
Ok :) let's pause #34 (anyway we already linked that in lime-package readme). For the name, is also the subdomain imagebuilder.libremesh.org going to change or just the "jefe" name?

**Comment by aparcar** [comment]
@ilario we decided to use chef.libremesh.org

**Comment by ilario** [comment]
@aparcar great, going to modify the PR #34

**Comment by ilario** [comment]
Wait, which will be the best URL? `https://chef.libremesh.org/imagebuilder` or `https://chef.libremesh.org`?

**Comment by ilario** [comment]
It's the second one.
