### ISSUE TITLE
Make cooker use 17.01.4

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-sdk#39]
There have been a couple of security upgrades within the last weeks. Cooker currently still uses 17.01.2.

**Comment by p4u** [comment]
Branch for 17.01.4 has been created, once it is tested we can merge it with master.

**Comment by ilario** [comment]
I think it was closed because of the merge of #48 into develop branch.

**Comment by p4u** [comment]
Actually 17.01.4 was merged into 'master' branch of cooker.
