### ISSUE TITLE
Branch for compiling with new web UI

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-sdk#44]
The new web interface developed by @gmarcos87 is based on LuCI2 and is located here:
https://github.com/libremesh/lime-packages-ui
and here:
https://github.com/libremesh/lime-app/

We need a branch for compiling an updated 17.01.4 LEDE with the new UI, it will be something like this old branch:
https://github.com/libremesh/lime-sdk/compare/luci2

Some notes:

* abandoned https://github.com/libremesh/lime-ui-ng has to be removed from feeds.conf.default
* new https://github.com/libremesh/lime-packages-ui has to be added to feeds.conf.default
* a new flavor has to be added, I don't know if the legacy webui can be there or should be excluded

**Comment by nicopace** [comment]
It is not based on LuCI2 ;) It is based on his own doing (using Preact and PWA)

**Comment by ilario** [comment]
Updates on this? @gmarcos87 @nicopace 
Do you think that the new webui will be default on upcoming release?

**Comment by nicopace** [comment]
Have already added it to lime_default profile!
You can close this 

On February 4, 2018 9:45:14 AM GMT-03:00, Ilario Gelmetti <notifications@github.com> wrote:
>Updates on this? @gmarcos87 @nicopace 
>Do you think that the new webui will be default on upcoming release?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/libremesh/lime-sdk/issues/44#issuecomment-362904109

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by ilario** [comment]
EPIC!
