### ISSUE TITLE
Migration to OpenWrt

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-sdk#49]
Mostly solved by #48 
LEDE is still mentioned in this repository here:
https://github.com/libremesh/lime-sdk/search?q=lede

**Comment by aparcar** [comment]
@patogit are you up for that job?

**Comment by patogit** [comment]
yes, I'm up for it, on Friday or next week. Looks like mostly just text replacement, plus some link checking and file name testing, shouldn't take long. The .gitignore file that mentions a `lede` directory looks potentially more complicated, as I don't see any such directory in the repo.

**Comment by nordurljosahvida** [comment]
Hi. I'm not sure what the intended behaviour is, but my images build with lime-sdk are still based on LEDE 17.01, why are they not using openwrt?

Thanks!

**Comment by ilario** [comment]
@nordurljosahvida upcoming release will be based on OpenWrt, but current stable release (Dayboot Rely, 17.06) is based on LEDE

**Comment by nordurljosahvida** [comment]
@ilario thanks for the info

**Comment by nordurljosahvida** [comment]
@ilario another question sorry, I see that on snapshots.libremesh.org some dev builds were based on 18.06, how could I reproduce the same result with sdk? I have a MIR3G which I've just gotten owrt installed onto, and I'd love to test it out with LiMe.

Thanks!

**Comment by ilario** [comment]
I don't know, let's ask @p4u @aparcar @nicopace @altergui

**Comment by nordurljosahvida** [comment]
cool thanks

**Comment by nordurljosahvida** [comment]
@ilario These routers are amazing by the way. They might not be libre as the LibreRouter but they're 30€ each, AC1200, very beautiful and small, and seem to work great with openwrt. It takes about 15 minutes to [flash openwrt](https://forum.openwrt.org/t/xiaomi-wifi-router-3g/5377/57) onto them as you need to enable SSH onto them first, but once that's done you're good to go. I think they'd be an amazing device for LiMe networks, especially given their excellent quality and price. I hope we can get a build for them soon! Thanks again for the help!

**Comment by ilario** [comment]
while we wait for @p4u's answer, you can try to compile using lime-sdk branch develop, maybe taking some changes from openwrt-18.06 branch for compiling on 18.06 rather than on trunk:

https://github.com/libremesh/lime-sdk/compare/develop...openwrt-18.06

**Comment by nordurljosahvida** [comment]
Perfect thanks! I've used the 18.06 branch as it is for now, to test things out, and I see the profile!

```
user@ubuntu:~/lime-sdk$ ./cooker --profiles=ramips/mt7621 | grep 3g
mikrotik_rbm33g:
mir3g:
```

**Comment by nordurljosahvida** [comment]
@ilario i'm having some issues on 18.06 on develop branch. when lime-config runs, it breaks meshing with other nodes. so if i just flash a node and start it up, it works. if i change the node name, either from web or from `/etc/config/lime`, then run `lime-config`, things break. resetting to defaults from backup/flash firmware page works. should i open an issue or would it just generate noise, being for 18.06? thanks again

**Comment by ilario** [comment]
I suggest to open a new issue, we will need the content of /etc/config/network and of /etc/config/wireless before and after. If there's nothing looking weird you can add some more of the info listed in libremesh/lime-packages#423

**Comment by nordurljosahvida** [comment]
ok great thanks

**Comment by ilario** [comment]
Some more has been addressed in #97

**Comment by ilario** [comment]
@p4u are you sure it is fixed?
There are still mentions to LEDE in Readme and in flavors.conf:
https://github.com/libremesh/lime-sdk/search?q=lede

**Comment by patogit** [comment]
current LibreMesh development by the LibreRouter team is happening [at this repo](https://github.com/LibreRouterOrg/openwrt/tree/librerouter-18.06) and is not using the lime-sdk, but instead the process described in the readme there.

**Comment by p4u** [comment]
> @p4u are you sure it is fixed?
> There are still mentions to LEDE in Readme and in flavors.conf:
> https://github.com/libremesh/lime-sdk/search?q=lede

Fixed!



> current LibreMesh development by the LibreRouter team is happening [at this repo](https://github.com/LibreRouterOrg/openwrt/tree/librerouter-18.06) and is not using the lime-sdk, but instead the process described in the readme there.

LibreMesh and LibreRouter are diferent projects. LibreMesh should be compatible with LibreRouter but also with many other devices. It makes sense that LibreRouter has its own specific tools, but LibreMesh should keep its generic behaviour (not dependent on any specific hardware device).

Cheers.

**Comment by patogit** [comment]
> LibreMesh should be compatible with LibreRouter but also with many other devices. It makes sense that LibreRouter has its own specific tools, but LibreMesh should keep its generic behaviour (not dependent on any specific hardware device).

I agree!!! I don't understand the function of lime-sdk given that now I'm using the OpenWrt method of making firmware (git clone, update feeds, install feeds, edit .config, make), which LibreRouter development uses too.
