### ISSUE TITLE
Add support for feeds.conf src options

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-sdk#50]
In https://wiki.openwrt.org/doc/devel/feeds openwrt sdk and ib support multiple feed fetching methods.
Giving support to at list src-link or src-spy will allow to have local repositories integrated within lime-sdk.

**Comment by p4u** [comment]
This is already possible be adding your own feeds in feeds.conf.default

There is a documentation about how to use your own feed in the README file of lime-sdk

**Comment by nicopace** [comment]
I tried it a few days ago and src-link and src-cpy where not working.
When I changed them to src-git it started working.

Could it be because it is not implemented here?
https://github.com/libremesh/lime-sdk/blob/master/cooker#L280

**Comment by p4u** [comment]
Ok, now I understand the issue.

And yes, it probably needs some changes in the code. However you can always use git in a local directory

Example of what I'm saying:

mkdir feed1
cd feed1
git init
cd ..
git clone ./feed1 feed2

At this point feed2 is a clone of feed1 and the remote is a local directory file.

**Comment by nicopace** [comment]
Yes, I was doing that... just wanted to state that it in order to comply with how openwrt defines the feeds.conf, there was some lacking. Not difficult dough'... could be left as an exercise for someone starting with lime-sdk :)

**Comment by p4u** [comment]
Ok, agreed.

Right now cooker ignores the non-git feeds 
https://github.com/libremesh/lime-sdk/blob/master/cooker#L280

That may be changed to support also more kind of feeds.

**Comment by nicopace** [comment]
This shouldn't be closed, as it is still a pending and useful feature. Reopening it.

**Comment by aparcar** [comment]
@nicopace please review PR

**Comment by aparcar** [comment]
fixed
