### ISSUE TITLE
Including OpenWrt repositories in libremesh.repositories.conf

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-sdk#54]
What about having OpenWrt/LEDE repositories additionally to our own packages repositories configured in libremesh.repositories.conf? As we're using the IB and SDK the packages will be compatible.
This would allow one to use cooker with remote packages download (--remote option) and adding packages not present in our repositories (--extra-pkg="pkg1 pkg2" option).
How can we assure that in case of name conflict (e.g. bmx6 package being present both in our and OpenWrt repository) the newest version or our version of the two is going to be used?

**Comment by aparcar** [comment]
I'd prefer to *only* build lime specific packages. Wouldn't it be possible to change our server settings to forward requests to `/base /packages/ /luci/ etc` to the official servers? So we don't actually build the stuff but still allow the `--remote` parameter.

**Comment by ilario** [comment]
Wait, I didn't propose to build non-LibreMesh packages, just to add the direction to the official repository (where OpenWrt people update their compiled packages).
