### ISSUE TITLE
libremesh repos are not working lime-sdk/libremesh.repositories.conf

### ISSUE THREAD

**Issue by bvujnovac** [libremesh/lime-sdk#57]
when using --remote option in cooker remote libremesh repository's return "not found"

output from shell:

Downloading http://repo.libremesh.org/current/packages/mips_24kc/libremesh/Packages.gz
*** Failed to download the package list from http://repo.libremesh.org/current/packages/mips_24kc/libremesh/Packages.gz

Downloading http://repo.libremesh.org/current/packages/mips_24kc/libremap/Packages.gz
*** Failed to download the package list from http://repo.libremesh.org/current/packages/mips_24kc/libremap/Packages.gz

Downloading http://repo.libremesh.org/current/packages/mips_24kc/limeui/Packages.gz
*** Failed to download the package list from http://repo.libremesh.org/current/packages/mips_24kc/limeui/Packages.gz

Downloading http://repo.libremesh.org/current/packages/mips_24kc/routing/Packages.gz
*** Failed to download the package list from http://repo.libremesh.org/current/packages/mips_24kc/routing/Packages.gz

Downloading http://repo.libremesh.org/network-profiles//Packages.gz
*** Failed to download the package list from http://repo.libremesh.org/network-profiles//Packages.gz

Collected errors:
 * opkg_download: Failed to download http://repo.libremesh.org/current/packages/mips_24kc/libremesh/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://repo.libremesh.org/current/packages/mips_24kc/libremap/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://repo.libremesh.org/current/packages/mips_24kc/limeui/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://repo.libremesh.org/current/packages/mips_24kc/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://repo.libremesh.org/network-profiles//Packages.gz, wget returned 8.

**Comment by aparcar** [comment]
Hey, that was a problem with the server misdirecting `http` traffic. Was fixed a few days ago
