### ISSUE TITLE
test lime-sdk on a clean system

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-sdk#7]
I'm doing a training for a new developer to step up and contribute to the project, and we found out that a lot of dependencies are required to have lime-sdk work.

We should be testing it on a bare installation of at least ubuntu and debian to ensure that it works.

The required packages can be found here: https://lede-project.org/docs/guide-developer/install-buildsystem

**Comment by p4u** [comment]
Link added to README on commit 72f46a4b9bcb92db0b2d577e6fb571ce30edf03e

**Comment by nicopace** [comment]
great, thanks!
